### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [fajrtech/csv_batch_import#1]
Problem

please fix Plugin home page: https://fajr.tech/ to reference links related to the plugin

**Comment by fajrtech** [comment]
On 2023-07-17 09:37, mazano wrote:

> #Problem
> 
> please fix Plugin home page: https://fajr.tech/
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you are subscribed to this 
> thread.Message ID: ***@***.***>

Hi,

Home page was fixed. Please check.



Links:
------
[1] https://github.com/fajrtech/csv_batch_import/issues/1
[2]

**Comment by fajrtech** [comment]
Hi,

I have not received any feedback from you since 3 days.

I have fixed the home page (https://fajr.tech/) as requested from you. 
Should I resubmit the plugin? But I think there is no need as I have 
made no changes in it.

Waiting for your reply,

Best regards,

Fajr

On 2023-07-23 15:50, ***@***.*** wrote:

> On 2023-07-17 09:37, mazano wrote:
> 
>> #Problem
>> 
>> please fix Plugin home page: https://fajr.tech/
>> 
>> --
>> Reply to this email directly, view it on GitHub [1], or unsubscribe 
>> [2].
>> You are receiving this because you are subscribed to this 
>> thread.Message ID: ***@***.***>
> 
> Hi,
> 
> Home page was fixed. Please check.



Links:
------
[1] https://github.com/fajrtech/csv_batch_import/issues/1
[2]

**Comment by NyakudyaA** [comment]
You need to resubmit so that those changes are visible on the plugin repo

**Comment by fajrtech** [comment]
Hi Mazano,

I have edited the Plugin's description at the QGIS plugins portal. 
Should I do something else?

As I mentioned the Pluign's source code has not been changed, so no need 
for resubmitting it, right?

On 2023-07-27 06:38, mazano wrote:

> You need to resubmit so that those changes are visible on the plugin 
> repo
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you commented.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/fajrtech/csv_batch_import/issues/1#issuecomment-1652997026
[2]

**Comment by NyakudyaA** [comment]
You need to update your zip, since the zip contains the metada.txt which will be the seen by the public

**Comment by fajrtech** [comment]
Hi Mazano,

I have uploaded a new version.

Thanks for your support.

Best regards,

Fajr

On 2023-07-29 20:00, mazano wrote:

> You need to update your zip, since the zip contains the metada.txt 
> which will be the seen by the public
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you commented.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/fajrtech/csv_batch_import/issues/1#issuecomment-1656864996
[2]

**Comment by NyakudyaA** [comment]
nothing  changed
![image](https://github.com/fajrtech/csv_batch_import/assets/2510900/604f2858-a4d9-4de3-8c04-936aeb02ea17)

**Comment by fajrtech** [comment]
I have fixed the website itself, so now fajr.tech is working.

On 2023-07-30 06:58, mazano wrote:

> nothing changed
> [1]
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you commented.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://user-images.githubusercontent.com/2510900/257037043-604f2858-a4d9-4de3-8c04-936aeb02ea17.png
[2] 
https://github.com/fajrtech/csv_batch_import/issues/1#issuecomment-1657061235
[3]

**Comment by NyakudyaA** [comment]
@fajrtech The idea of a homepage is not to have a working link for your website. We need to have a page on your website that talks about the plugin. If you do not have this you can just reference the repo as your plugin homepage

Example below
![image](https://github.com/fajrtech/csv_batch_import/assets/2510900/656ec564-f929-4998-b081-4820fb124cd4)

**Comment by fajrtech** [comment]
Hi Mazano,

Thanks for your support.

I have uploaded a new version with the home page set to the github 
repository.

On 2023-08-02 06:52, mazano wrote:

> @fajrtech [1] The idea of a homepage is not to have a working link for 
> your website. We need to have a page on your website that talks about 
> the plugin. If you do not have this you can just reference the repo as 
> your plugin homepage
> 
> Example below
> [2]
> 
> --
> Reply to this email directly, view it on GitHub [3], or unsubscribe 
> [4].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>



Links:
------
[1] https://github.com/fajrtech
[2] 
https://user-images.githubusercontent.com/2510900/257726285-656ec564-f929-4998-b081-4820fb124cd4.png
[3] 
https://github.com/fajrtech/csv_batch_import/issues/1#issuecomment-1661602009
[4]
